// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CreateProduct(ctx context.Context, arg CreateProductParams) (Product, error)
	CreateShelf(ctx context.Context, arg CreateShelfParams) (Shelf, error)
	DeleteShelfById(ctx context.Context, id int32) (Shelf, error)
	FindProductByName(ctx context.Context, dollar_1 pgtype.Text) ([]Product, error)
	GetProductByCategory(ctx context.Context, category pgtype.Text) ([]Product, error)
	//-----------------------------------------------
	// PRODUCT TABLE
	//-----------------------------------------------
	GetProductById(ctx context.Context, id int32) (Product, error)
	GetProductBySku(ctx context.Context, sku string) (Product, error)
	GetProductExpired(ctx context.Context, expiredDate pgtype.Timestamp) ([]Product, error)
	GetProductNotExpired(ctx context.Context, expiredDate pgtype.Timestamp) ([]Product, error)
	//-----------------------------------------------
	// SHELF TABLE
	//-----------------------------------------------
	GetShelfById(ctx context.Context, id int32) (Shelf, error)
	GetShelfByProductId(ctx context.Context, productID int32) ([]Shelf, error)
	GetShelfBySku(ctx context.Context, sku string) ([]Shelf, error)
	GetShelfBySkuAndName(ctx context.Context, arg GetShelfBySkuAndNameParams) (Shelf, error)
	UpdateProduct(ctx context.Context, arg UpdateProductParams) (Product, error)
	UpdateShelf(ctx context.Context, arg UpdateShelfParams) (Shelf, error)
}

var _ Querier = (*Queries)(nil)
