// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package store

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Transaction struct {
	ID int32 `json:"id"`
	// Action is stored as integer. Mapping between action and integer must be documented somewhere else.
	Action    int32            `json:"action"`
	Date      pgtype.Timestamp `json:"date"`
	Sku       string           `json:"sku"`
	ShelfName string           `json:"shelf_name"`
	Quantity  int32            `json:"quantity"`
	AuthorID  int32            `json:"author_id"`
}

type User struct {
	ID   int32  `json:"id"`
	Name string `json:"name"`
}
