// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CreateTransaction(ctx context.Context, arg CreateTransactionParams) (Transaction, error)
	CreateUser(ctx context.Context, name string) (User, error)
	FindUserByName(ctx context.Context, dollar_1 pgtype.Text) ([]User, error)
	//-----------------------------------------------
	// TRANSACTION TABLE
	//-----------------------------------------------
	GetTransactionById(ctx context.Context, id int32) (Transaction, error)
	GetTransactionsByAuthorId(ctx context.Context, authorID int32) ([]Transaction, error)
	GetTransactionsByAuthorName(ctx context.Context, name string) ([]Transaction, error)
	GetTransactionsBySku(ctx context.Context, sku string) ([]Transaction, error)
	GetTransactionsByStartAndEndDate(ctx context.Context, arg GetTransactionsByStartAndEndDateParams) ([]Transaction, error)
	GetUserByExactName(ctx context.Context, name string) (User, error)
	//-----------------------------------------------
	// USER TABLE
	//-----------------------------------------------
	GetUserById(ctx context.Context, id int32) (User, error)
}

var _ Querier = (*Queries)(nil)
